### ISSUE TITLE
SigProfilerMatrixGeneratorR wrapper problem

### ISSUE THREAD

**Issue by Snottley** [AlexandrovLab/SigProfilerMatrixGeneratorR#4]
I am trying to run the matrix generator and I am receiving this error message:

Error in py_call_impl(callable, dots$args, dots$keywords) :
  UnboundLocalError: local variable 'samples' referenced before assignment

Detailed traceback:
  File "/lustre/scratch/scratch/regmswg/Software/miniconda2/envs/SigProfiler/lib/python3.5/site-packages/SigProfilerMatrixGenerator/scripts/SigProfilerMatrixGeneratorFunc.py", line 371, in SigProfilerMatrixGe$    samples = sorted(samples)
Calls: SigProfilerMatrixGeneratorR -> <Anonymous> -> py_call_impl
Execution halted

This is the code I have used:

library("SigProfilerMatrixGeneratorR")

SigProfilerMatrixGeneratorR("test_VORTEX", "GRCh37", "/home/regmswg/Scratch/Projects/SigProfiler/test_VORTEX/",
plot=T, exome=F, bed_file=NULL, chrom_based=F, tsb_stat=F, seqInfo=F, cushion=100)

I am using python 3.5, and R version 3.6.

Could you please help with troubleshooting? Many thanks. Steven

**Comment by ebergstr** [comment]
It is difficult to debug this issue based off of the given error without more details. I suspect that the issue may be arising do the formatting of the input files. Can you please check that your file formats adhere to one of the four example input file formats (along with the proper file name extension - i.e. ".vcf" for vcf files) provided on the wiki page? If your issue persists can you please email an example of one of your input files to ebergstr@eng.ucsd.edu so that we can debug from our end? Patient/sample ID's can be de-identified if necessary.

**Comment by ebergstr** [comment]
We are assuming that this issue has been resolved; however, please do not hesitate to reopen the issue if additional assistance is required. 

Best,
Erik
